# Generated by Django 4.2.21 on 2025-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
