# Generated by Django 4.2.21 on 2025-05-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow_app', '0003_cashflow_created_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow_app.type'),
            preserve_default=False,
        ),
    ]
