# Generated by Django 4.2.21 on 2025-05-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow_app', '0004_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
