# Generated by Django 4.2.21 on 2025-05-31 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('cashflow_app', '0005_alter_cashflow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='card.account'),
            preserve_default=False,
        ),
    ]
